### ISSUE TITLE
Issue with tag item

### ISSUE THREAD

**Issue by nemodym** [shuiRong/vue-drag-tree#13]
I am getting this error when trying to use vue-drag-tree. In the template of the vue-drag-tree component I see a tag "item". Not sure what tag that is. I don't see that it is a custom component tag, nor is it a valid html tag. Please clarify. Thanks!

vue.esm.js?efeb:578 [Vue warn]: Failed to mount component: template or render function not defined.

found in

 \<Item\>
       \<VueDragTreeCom42\> at node_modules/vue-drag-tree/src/vue-drag-tree.vue

**Comment by laputafish** [comment]
This component looks amazing but when I tried, the following error occurs. Don't know how to fix it.
Any advice.
----------  
 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Item>
       <VueDragTreeCom42> at node_modules\vue-drag-tree\src\vue-drag-tree.vue
         <VueDragTree> at src\views\custom\VueDragTree.vue
           <Anonymous>
             <Full> at src\containers\Full.vue
               <App> at src\App.vue
                 <Root>
----------

**Comment by shuiRong** [comment]
I rewrote this project, so this problem was gone.
