### ISSUE TITLE
怎么运行起来啊 

### ISSUE THREAD

**Issue by pengmingtao** [shuiRong/vue-drag-tree#14]

**Comment by shuiRong** [comment]
首先，用npm安装到本地，然后....[参考文档 快速开始 ](https://github.com/shuiRong/vue-drag-tree/blob/master/README_ZH.md) ，另外我写了个[demo](https://github.com/shuiRong/vue-drag-tree-demo)，可以看我代码怎么写的。

**Comment by shuiRong** [comment]
另外，项目有个bug导致使用时会出问题，还没来得及修补。如果不是你个人项目需要用的话，建议先使用其他的开发组件吧。Element-UI最近更新后，[Tree组件](http://element.eleme.io/#/zh-CN/component/tree)也增加了拖拽功能，实现的不错，你可以尝试下
