### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by annettaws** [shuiRong/vue-drag-tree#17]
Hi i'm using your lib, that is light and easy.
I suggest you to update the documentation: the event emitted to check the current node clicked is @current-node-clicked and not @current-clicked.

I suggest you also and allowNewItem to enable/disable the double-click adding of you Item.

Bye

**Comment by sabbirsr** [comment]
Thank you so mutch @annettaws :) i am also faching this problem solve now :100:

**Comment by shuiRong** [comment]
@annettaws @sabbirsr  Thanks for feedback. 
The documentation has been updated. And the `disableDoubleClick` property has been added.
