### ISSUE TITLE
<item> is html5 element?

### ISSUE THREAD

**Issue by Rainnut** [shuiRong/vue-drag-tree#18]
![image](https://user-images.githubusercontent.com/12372532/46589678-14c87780-cadf-11e8-8a51-311998c3d8fa.png)

I don't know what label element < item > is. HTML 5 has a < menuItem > label, but it doesn't look like the same thing. 
Could you tell me how to use the <item> element？？

**Comment by shuiRong** [comment]
It's a Vue's component.
https://github.com/shuiRong/vue-drag-tree/blob/master/src/DragNode.vue
```
 beforeCreate() {
    this.$options.components.item = require('./DragNode.vue')
  },
```
[Vue Component](https://cn.vuejs.org/v2/guide/components-registration.html)
