### ISSUE TITLE
npm  run  dev  报错

### ISSUE THREAD

**Issue by lcting** [shuiRong/vue-drag-tree#21]
![image](https://user-images.githubusercontent.com/35803577/50071259-195e8a00-020c-11e9-8d9c-b9156f5aaaa5.png)

![image](https://user-images.githubusercontent.com/35803577/50071277-2d09f080-020c-11e9-9428-9685caa9db6a.png)

![image](https://user-images.githubusercontent.com/35803577/50071295-3d21d000-020c-11e9-84a4-32042c936b01.png)

![image](https://user-images.githubusercontent.com/35803577/50071307-47dc6500-020c-11e9-8b47-b5024973e7c5.png)

**Comment by shuiRong** [comment]
你用错了。
首先不需要把代码copy到你的项目中（见最后一张截图）。
这儿有一个使用这个组件的[完整项目](https://github.com/shuiRong/vue-drag-tree-demo)，你clone并运行下，看看这里面是如何使用的。

P.S. 注意报错说变量`data`未定义，你代码中确保存在这个变量

**Comment by shuiRong** [comment]
@lcting [这儿有所有的仓库](https://github.com/shuiRong?tab=repositories)，你可以翻翻看

**Comment by lcting** [comment]
好的，多谢大佬
