### ISSUE TITLE
Error in wiki how use need fix it and 

### ISSUE THREAD

**Issue by andysay** [shuiRong/vue-drag-tree#7]
now is 	<vue-darg-tree :model='data'　:current-highlight='true' :default-text='"New A Girl"' :hover-color='"lightblue"' :highlight-color='green'></vue-drag-tree>

need <vue-darg-tree > change to <vue-drag-tree>

and when i try use this 

i  have next error [Vue warn]: Failed to mount component: template or render function not defined.

vue.runtime.esm.js:472 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Item>
       <VueDragTreeCom42> at node_modules/vue-drag-tree/src/vue-drag-tree.vue
         <ICol>
           <Row>

**Comment by jtwheadon** [comment]
Did you ever find a solution to this?

**Comment by shuiRong** [comment]
Sorry.@jtwheadon  @andysay 
I will fix it in the few days. 

(work++)

**Comment by shuiRong** [comment]
@andysay @jtwheadon 
Hi, Guys. 
I find the reason of `Failed to mount component: template or render function not defined.`
It's a spelt error in wikihow: `<drag-....` not `<darg...` 
Fixed
