### ISSUE TITLE
点击Tree上的按钮报错

### ISSUE THREAD

**Issue by tlxcdl123** [shuiRong/vue-drag-tree#8]
你好， 按照你的说的方式，调用了这个组件 但是 点击Root 或者+ 号时 报错
(点击Root)
Uncaught TypeError: Cannot set property 'background' of undefined
    at VueComponent.toggle (vue-drag-tree.vue?db22:70)
    at boundFn (vue.esm.js?efeb:186)
    at invoker (vue.esm.js?efeb:1943)
    at HTMLDivElement.fn._withTask.fn._withTask (vue.esm.js?efeb:1778)
(点击+号）
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Item>
       <VueDragTreeCom42> at node_modules\vue-drag-tree\src\vue-drag-tree.vue
         <Hello> at src\components\Hello.vue
           <App> at src\App.vue
             <Root>
warn @ vue.esm.js?efeb:571

我vue-cli 脚手架的搭建是 npm init webpack-simple xxxx
                                          npm install 
然后就按照说明使用组件，报错了
我下了一个你的demo(vue-drag-tree-demo)工程 运行时就没问题，能受累帮忙看看怎么回事么？
main.js
--------------------------------------------
import Vue from 'vue'
import App from './App.vue'

import router from './router'
import TreeView from 'vue-json-tree-view'
import VueDragTree from 'vue-drag-tree'
Vue.component('vue-drag-tree', VueDragTree)
Vue.config.productionTip = false
Vue.use(TreeView)
new Vue({
  // el: '#app',
  // router,
  // render: h => h(App)
  el: '#app',
  router,
  template: '<App/>',
  components: {
      App
  }
})
-------------------------------------------------
App.vue 跟你的demo工程是一样的

**Comment by shuiRong** [comment]
重构了项目
